import {money} from './products.js';
import {escapeHtml as h} from './ui.js';
import {icon} from './icons.js?v=admin-manage-20261005';

export function renderAdminLogin(message=''){
  return `<section class="admin-login-page"><div class="admin-login-art"><a class="admin-brand"><span class="brand-mark">b<span>.</span></span><span class="brand-copy"><b>BREW & CO.</b><small>STAFF PORTAL</small></span></a><div class="login-art-copy"><span class="kiosk-kicker">BEHIND EVERY GOOD CUP</span><h1>Made with care.<br><em>Run with care.</em></h1><p>Your orders, menu and daily service in one quiet workspace.</p><div class="login-orbit"><div class="orbit-cup">${icon('coffee')}</div><span class="orbit-dot dot-a"></span><span class="orbit-dot dot-b"></span><span class="orbit-dot dot-c"></span></div></div><small class="login-privacy">BREW & CO. · STAFF ACCESS ONLY</small></div><div class="admin-login-panel"><form id="adminLoginForm" class="login-card"><a class="login-back" href="/" data-action="go-home">${icon('arrowLeft')} Back to customer menu</a><span class="eyebrow">${icon('help')} SECURE ADMIN ACCESS</span><h2>Welcome back.</h2><p class="login-subtitle">Sign in to manage the café and keep orders moving.</p><label for="adminEmail">Email address</label><input id="adminEmail" name="email" type="email" autocomplete="username" placeholder="you@brewco.com" required maxlength="254"><label for="adminPassword">Password</label><div class="password-wrap"><input id="adminPassword" name="password" type="password" autocomplete="current-password" placeholder="Enter your password" required maxlength="256"><button type="button" class="show-password" aria-label="Show password">Show</button></div>${message?`<div class="login-error" role="alert">${h(message)}</div>`:''}<button class="login-submit" type="submit"><span>Sign in to dashboard</span>${icon('arrow')}</button><p class="login-footnote">${icon('receipt')} Protected staff workspace · Session expires after 8 hours</p></form></div></section>`;
}

export function renderAdminDashboard(email,orders=[],tab='orders',menu=null,contact=null,users=[],messages=[]){
  const tabs=[['orders','receipt','Orders'],['products','coffee','Products'],['categories','sparkle','Categories'],['contact','contact','Contact'],['messages','receipt','Messages'],['users','about','Users'],['settings','receipt','Menu settings']];
  const count=status=>orders.filter(order=>order.status===status).length;
  const content=tab==='products'?renderProducts(menu):tab==='categories'?renderCategories(menu):tab==='contact'?renderContact(contact):tab==='messages'?renderMessages(messages):tab==='users'?renderUsers(users):tab==='settings'?renderMenuSettings(menu):renderOrders(orders);
  return `<section class="admin-layout"><aside class="admin-sidebar"><a href="/" class="admin-sidebar-brand"><span class="brand-mark">b<span>.</span></span><span><b>BREW & CO.</b><small>STAFF WORKSPACE</small></span></a><div class="sidebar-section-label">MANAGE YOUR CAFÉ</div><nav class="admin-nav" aria-label="Admin sections">${tabs.map(([id,glyph,label])=>`<button type="button" class="sidebar-item ${tab===id?'current':''}" data-admin-tab="${id}">${icon(glyph)}<span>${label}</span>${id==='orders'?`<i>${orders.length}</i>`:''}</button>`).join('')}</nav><a class="sidebar-item admin-customer-link" href="/" target="_blank" rel="noreferrer">${icon('home')}<span>Customer menu</span>${icon('arrow')}</a><div class="sidebar-bottom"><div class="admin-avatar">${h((email[0]||'A').toUpperCase())}</div><div class="admin-identity"><b>Administrator</b><small>${h(email)}</small></div><button class="logout-button" id="adminLogout" title="Sign out" aria-label="Sign out">${icon('arrowLeft')}</button></div></aside><main class="admin-main"><header class="dashboard-top"><div><span class="dashboard-date">${new Date().toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</span><h1>Good day, Admin <span>${icon('sparkle')}</span></h1><p>Manage orders, drinks and café information.</p></div><div class="dashboard-tools"><button id="adminCameraToggle" class="refresh-button admin-camera-button" type="button" aria-label="Enable camera hand controls">${icon("camera")} <span>Hand control</span></button><span class="live-indicator"><i></i> LIVE ORDERS</span><button id="refreshOrders" class="refresh-button" type="button">${icon('arrow')} <span>Refresh</span></button></div></header><div class="admin-stats">${[['PENDING','New orders','coral','receipt'],['PREPARING','In progress','amber','coffee'],['READY','Ready','mint','check'],['COMPLETED','Completed','slate','check']].map(([status,label,color,glyph])=>`<article class="stat-card"><span class="stat-icon ${color}">${icon(glyph)}</span><span class="stat-label">${label}</span><b data-status-count="${status}">${count(status)}</b><small>${label==='New orders'?'Waiting for a barista':label==='In progress'?'Being prepared':label==='Ready'?'Ready to hand over':'Orders fulfilled'}</small></article>`).join('')}</div><section class="admin-workspace"><header class="workspace-heading"><div><span class="eyebrow">${icon(tabs.find(item=>item[0]===tab)?.[1]||'sparkle')} CAFÉ WORKSPACE</span><h2>${tabs.find(item=>item[0]===tab)?.[2]||'Orders'}</h2></div>${tab==='orders'?`<label class="admin-search">${icon('search')}<input id="orderSearch" placeholder="Search orders" aria-label="Search orders"></label>`:''}</header>${content}</section><footer class="dashboard-footer"><span>Order updates refresh automatically every 5 seconds</span><span>BREW & CO. · STAFF ONLY</span></footer></main></section>`;
}

function renderMessages(messages){
  if(!messages.length)return `<section class="admin-panel"><div class="admin-empty-state">${icon('contact')}<b>No customer messages yet</b><span>Messages sent from the customer Contact page will appear here.</span></div></section>`;
  return `<section class="admin-panel"><div class="panel-heading"><div><h3>Customer messages</h3><p>${messages.length} recent message${messages.length===1?'':'s'} from the storefront.</p></div>${icon('contact')}</div><div class="message-inbox">${messages.map(message=>`<article class="inbox-message"><header><div><b>${h(message.name)}</b><a href="mailto:${h(message.email)}">${h(message.email)}</a></div><time>${h(new Date(message.createdAt).toLocaleString())}</time></header>${message.subject?`<h4>${h(message.subject)}</h4>`:''}<p>${h(message.message).replace(/\n/g,'<br>')}</p></article>`).join('')}</div></section>`;
}

function renderOrders(orders){
  const groups=[['PENDING','New orders','Waiting for preparation'],['PREPARING','In progress','Being prepared'],['READY','Ready for pickup','Ready to hand over'],['COMPLETED','Completed','Recently fulfilled']];
  return `<p class="workspace-hint">Pinch and hold an order card, move it to a status column, then release to update its status.</p><div class="queue-board">${groups.map(([status,title,subtitle])=>{const list=orders.filter(order=>order.status===status);return `<section class="queue-column" data-drop-status="${status}"><header class="queue-column-head"><div><h3>${title}</h3><small>${subtitle}</small></div><span class="queue-count">${list.length}</span></header><div class="queue-cards" data-queue="${status}">${list.length?list.map(order=>orderCard(order)).join(''):`<div class="queue-empty"><span>${icon(status==='PENDING'?'receipt':'coffee')}</span><p>No ${title.toLowerCase()}</p></div>`}</div></section>`}).join('')}</div>`;
}

function orderCard(order){
  return `<article class="admin-order-card" data-order-id="${h(order.id)}" data-hand-target tabindex="0" aria-label="Order ${h(order.id)}. Pinch and move to change status." data-search-text="${h(`${order.id} ${order.items.map(item=>item.name).join(' ')}`.toLowerCase())}"><div class="order-card-heading"><div><span class="order-number">${h(order.id)}</span><small>${new Date(order.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div><span class="order-status-dot ${order.status.toLowerCase()}" aria-label="${h(order.status)}"></span></div><div class="admin-order-items">${order.items.map(item=>`<div class="admin-order-item"><img class="admin-order-product-image" src="${h(item.image)}" alt="${h(item.name)}"><span><b>${item.quantity}×</b> ${h(item.name)}<small>${h(Object.values(item.optionLabels||{}).flat().join(' · '))}</small></span><strong>${money(item.quantity*item.unitPrice)}</strong></div>`).join('')}</div><div class="admin-order-bottom"><b>Total <span>${money(order.total)}</span></b><label class="sr-only" for="status-${h(order.id)}">Order status</label><select id="status-${h(order.id)}" data-status-id="${h(order.id)}" aria-label="Update ${h(order.id)} status">${[['PENDING','New'],['PREPARING','Preparing'],['READY','Ready'],['COMPLETED','Complete']].map(([value,label])=>`<option value="${value}" ${order.status===value?'selected':''}>${label}</option>`).join('')}</select></div></article>`;
}

function renderProducts(menu){
  if(!menu)return loadingAdminData();
  const categories=menu.categories||[...new Set(menu.products.map(product=>product.category))];
  return `<div class="admin-content-grid"><section class="admin-panel"><div class="panel-heading"><div><h3>Your products</h3><p>${menu.products.length} drinks in the menu</p></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Availability</th><th></th></tr></thead><tbody>${menu.products.map(product=>`<tr><td><div class="admin-product-cell"><img src="${h(product.image)}" alt=""><span><b>${h(product.name)}</b><small>${h(product.id)}</small></span></div></td><td>${h(product.category)}</td><td>${money(product.price)}</td><td><span class="availability-pill ${product.available?'is-available':'is-unavailable'}">${product.available?'Available':'Hidden'}</span></td><td class="admin-row-actions"><button type="button" class="mini-button" data-edit-product="${h(product.id)}">Edit</button><button type="button" class="mini-button" data-toggle-product="${h(product.id)}">${product.available?'Hide':'Show'}</button><button type="button" class="mini-button danger" data-delete-product="${h(product.id)}" aria-label="Delete ${h(product.name)}">${icon('trash')}</button></td></tr>`).join('')}</tbody></table></div></section><section class="admin-panel admin-form-panel"><div class="panel-heading"><div><h3 id="productFormHeading">Add a drink</h3><p>Product photos can be local or hosted image URLs.</p></div></div><form id="productForm" class="admin-form"><input type="hidden" name="originalId"><label>Product name<input name="name" required maxlength="100" placeholder="Honey oat latte"></label><label>Category<select name="category" required>${categories.map(category=>`<option value="${h(category)}">${h(category)}</option>`).join('')}</select></label><label>Price (USD)<input name="price" type="number" min="0" max="10000" step="0.01" required placeholder="4.50"></label><label>Image path or URL<input name="image" required maxlength="1000" placeholder="/img/coffee1.png"></label><label>Description<textarea name="description" rows="3" maxlength="500" placeholder="Describe this drink"></textarea></label><fieldset class="customization-checks"><legend>Available customizations</legend>${['size','temperature','sugar','milk','addons'].map(value=>`<label><input type="checkbox" name="customizations" value="${value}" checked><span>${value==='addons'?'Extras':value[0].toUpperCase()+value.slice(1)}</span></label>`).join('')}</fieldset><label class="check-row"><input name="available" type="checkbox" checked> Available to order</label><div class="form-actions"><button class="primary-button" type="submit">Save product</button><button class="secondary-button" type="reset" data-reset-product>Clear</button></div></form></section></div>`;
}

function renderCategories(menu){
  if(!menu)return loadingAdminData();
  const categories=menu.categories||[...new Set(menu.products.map(product=>product.category))];
  return `<section class="admin-panel"><div class="panel-heading"><div><h3>Menu categories</h3><p>Products stay in the menu category you assign to them.</p></div></div><form id="categoryForm" class="inline-admin-form"><label class="sr-only" for="newCategory">New category name</label><input id="newCategory" name="category" required maxlength="40" placeholder="Add a category, e.g. Cold brew"><button class="primary-button" type="submit">${icon('plus')} Add category</button></form><div class="category-admin-grid">${categories.map(category=>{const count=menu.products.filter(product=>product.category===category).length;return `<article class="category-admin-card"><span>${icon('coffee')}</span><div><b>${h(category)}</b><small>${count} product${count===1?'':'s'}</small></div><button class="mini-button" type="button" data-rename-category="${h(category)}">Rename</button><button class="mini-button danger" type="button" data-delete-category="${h(category)}" ${count?'disabled title="Move its products to another category first"':''}>${icon('trash')} Remove</button></article>`}).join('')}</div></section>`;
}

function renderContact(contact){
  if(!contact)return loadingAdminData();
  return `<section class="admin-panel admin-form-panel contact-admin-panel"><div class="panel-heading"><div><h3>Customer-facing café details</h3><p>These details are saved with your menu for the storefront.</p></div>${icon('contact')}</div><form id="contactForm" class="admin-form admin-contact-form"><label>Café name<input name="name" value="${h(contact.name||'Brew & Co.') }" required maxlength="120"></label><label>Contact email<input name="email" type="email" value="${h(contact.email||'')}" maxlength="254" placeholder="hello@yourcafe.com"></label><label>Phone number<input name="phone" type="tel" value="${h(contact.phone||'')}" maxlength="40" placeholder="+1 555 123 4567"></label><label>Address<input name="address" value="${h(contact.address||'')}" maxlength="240" placeholder="Street, city"></label><label>Opening hours<input name="hours" value="${h(contact.hours||'')}" maxlength="160" placeholder="Mon–Sat, 7am–6pm"></label><label>Website<input name="website" type="url" value="${h(contact.website||'')}" maxlength="240" placeholder="https://yourcafe.com"></label><div class="form-actions"><button class="primary-button" type="submit">${icon('check')} Save café details</button></div></form></section>`;
}

function renderUsers(users){
  if(!users)return loadingAdminData();
  return `<div class="admin-content-grid users-layout"><section class="admin-panel"><div class="panel-heading"><div><h3>Customer records</h3><p>${users.length} saved contact${users.length===1?'':'s'}. These are records, not sign-in accounts.</p></div></div>${users.length?`<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th></th></tr></thead><tbody>${users.map(user=>`<tr><td><b>${h(user.name)}</b></td><td>${h(user.email)}</td><td>${h(user.phone||'—')}</td><td class="admin-row-actions"><button class="mini-button" type="button" data-edit-user="${user.id}">Edit</button><button class="mini-button danger" type="button" data-delete-user="${user.id}">${icon('trash')}</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="admin-empty-state">${icon('about')}<b>No customer records yet</b><span>Add a customer contact with the form.</span></div>`}</section><section class="admin-panel admin-form-panel"><div class="panel-heading"><div><h3 id="userFormHeading">Add customer</h3><p>Save a name and contact details.</p></div></div><form id="userForm" class="admin-form"><input type="hidden" name="id"><label>Full name<input name="name" required maxlength="120" placeholder="Alex Smith"></label><label>Email address<input name="email" type="email" required maxlength="254" placeholder="alex@example.com"></label><label>Phone number<input name="phone" type="tel" maxlength="40" placeholder="Optional"></label><div class="form-actions"><button class="primary-button" type="submit">${icon('plus')} Save customer</button><button class="secondary-button" type="reset">Clear</button></div></form></section></div>`;
}

function renderMenuSettings(menu){
  if(!menu)return loadingAdminData();
  return `<section class="admin-panel admin-form-panel"><div class="panel-heading"><div><h3>Menu pricing</h3><p>Set the service fee and the price for each customization.</p></div>${icon('receipt')}</div><form id="menuSettingsForm" class="admin-form"><label>Service fee (USD)<input name="service" type="number" min="0" max="1000" step="0.01" value="${Number(menu.fees?.service||0).toFixed(2)}"></label><div class="option-pricing-groups">${Object.entries(menu.options).map(([group,options])=>`<fieldset class="option-pricing-group"><legend>${h(group==='addons'?'Extras':group[0].toUpperCase()+group.slice(1))}</legend>${options.map(option=>`<label>${h(option.label)}<span class="money-input"><span>$</span><input type="number" min="0" step="0.01" name="${h(group)}:${h(option.id)}" value="${Number(option.price||0).toFixed(2)}" aria-label="${h(option.label)} price"></span></label>`).join('')}</fieldset>`).join('')}</div><div class="form-actions"><button class="primary-button" type="submit">${icon('check')} Save menu prices</button></div></form></section>`;
}

function loadingAdminData(){return `<div class="admin-empty-state">${icon('clock')}<b>Loading café settings…</b></div>`;}
