import {money} from './products.js';
import {escapeHtml as h} from './ui.js';
import {icon} from './icons.js?v=admin-manage-20261005';

export function renderCustomerHome(menu,category,query){
  const visible=menu.products.filter(p=>(category==='All Coffee'||p.category===category)&&(`${p.name} ${p.description}`.toLowerCase().includes(query.toLowerCase())));
  const categories=['All Coffee',...new Set(menu.products.map(p=>p.category))];
  const contact=menu.contact||{};
  const contactDetails=[['location',contact.address],['clock',contact.hours],['contact',contact.phone],['contact',contact.email],['arrow',contact.website]].filter(([,value])=>value).map(([glyph,value])=>`<span>${icon(glyph)}${h(value)}</span>`).join('');
  const categoryButtons=categories.map(c=>`<button class="menu-filter ${category===c?'selected':''}" data-category="${h(c)}">${icon(c==='Matcha'||c==='Tea'?'leaf':'coffee')}<span>${h(c)}</span></button>`).join('');
  const productCards=visible.map(p=>`<article class="story-product-card"><button class="story-product-photo" data-action="detail" data-id="${h(p.id)}" aria-label="View and customize ${h(p.name)}"><img src="${h(p.image)}" alt="${h(p.name)}" loading="lazy"><span class="photo-view">View drink ${icon('arrow')}</span></button><div class="story-product-info"><div><h3>${h(p.name)}</h3><span>${icon('coffee')}${h(p.category)}</span></div><strong>${money(p.price)}</strong><button class="story-quick-add" data-action="quick-add" data-id="${h(p.id)}" aria-label="Add ${h(p.name)} to bag" ${p.available?'':'disabled'}>${icon('plus')}<b>Add</b></button></div><p class="story-product-description">${h(p.description)}</p><button class="story-order-button" data-action="detail" data-id="${h(p.id)}" ${p.available?'':'disabled'}>${icon('sparkle')}Customize drink ${icon('arrow')}</button></article>`).join('');
  const gallery=menu.products.slice(0,4).map((p,i)=>`<figure class="gallery-tile gallery-tile-${i+1}"><img src="${h(p.image)}" alt="${h(p.name)}" loading="lazy"><figcaption>${icon('coffee')}${h(p.name)}</figcaption></figure>`).join('');
  return `<div class="story-home">
    <section class="story-hero" id="home"><div class="story-hero-copy"><span class="story-eyebrow">${icon('sparkle')} SPECIALTY COFFEE HOUSE</span><h1>Where Every Cup<br>Tells a <em>Story</em></h1><p>Hand-crafted beverages made with single-origin beans, brewed with intention and served with warmth.</p><div class="story-hero-actions"><button class="story-primary" data-action="browse">${icon('coffee')}Explore our menu ${icon('arrow')}</button><a class="story-secondary" href="#about" data-section="about">${icon('about')}Our story</a></div><div class="hero-bean-note">${icon('leaf')} Thoughtfully sourced &middot; freshly made</div></div><div class="story-hero-image"><img src="https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1400&q=90" alt="Coffee served in a warm, leafy cafe"><span class="origin-tag">${icon('location')} Ethiopia &middot; Single origin</span><div class="hero-cup-mark" aria-hidden="true">${icon('coffee')}</div><div class="today-special"><small>${icon('sparkle')} TODAY'S SPECIAL</small><b>Honey oat latte</b></div></div></section>
    <section class="story-menu-section" id="menu"><div class="story-section-heading"><span class="story-eyebrow">${icon('sparkle')} SOMETHING GOOD IS BREWING</span><h2>Our coffee</h2><p>Good beans, a thoughtful hand, and a little time.</p></div><div class="menu-tools"><div class="menu-filters" aria-label="Filter coffee menu">${categoryButtons}</div><label class="story-search">${icon('search')}<input id="search" placeholder="Search your favorite coffee" value="${h(query)}" aria-label="Search coffee menu"></label></div><div class="story-product-grid">${productCards||`<div class="menu-empty">${icon('coffee')}<h3>No drinks found</h3><p>Try another category or search.</p></div>`}</div></section>
    <section class="story-about-section" id="about"><div class="about-photo"><img src="https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1000&q=85" alt="A freshly prepared coffee on a cafe counter" loading="lazy"><span>${icon('leaf')} BREWED WITH INTENTION</span></div><div class="about-copy"><span class="story-eyebrow">${icon('about')} A LITTLE ABOUT US</span><h2>Good coffee is<br>better <em>together.</em></h2><p>We believe a well-made cup can turn an ordinary pause into a favorite part of the day. We choose thoughtful beans, prepare each drink fresh, and make room for everyone at our table.</p><button class="story-secondary-button" data-action="browse">${icon('coffee')}Find your next favorite ${icon('arrow')}</button></div></section>
    <section class="story-gallery-section" id="gallery"><div class="story-section-heading"><span class="story-eyebrow">${icon('gallery')} A MOMENT FROM OUR COUNTER</span><h2>Made to be savored.</h2></div><div class="story-gallery-grid">${gallery}</div></section>
    <section class="story-contact-section"><span class="story-eyebrow">${icon('location')} YOUR COFFEE BREAK IS WAITING</span><h2>${h(contact.name||'Come on in.')}<br><em>Stay a little.</em></h2><p>Choose something lovely from the menu and we'll make it fresh for you.</p>${contactDetails?`<div class="story-contact-details">${contactDetails}</div>`:''}<button class="story-primary" data-action="browse">${icon('coffee')}Order a coffee ${icon('arrow')}</button></section>
    <footer class="story-footer"><a class="story-footer-brand" href="#home" data-section="home">Brewed <em>&amp;</em> Co.</a><span>${icon('sparkle')} Small moments, made beautifully.</span><button class="footer-gesture" data-action="help">${icon('hand')} Camera &amp; gestures</button><button class="footer-admin" data-action="admin-login">${icon('about')} Admin sign in</button><span>&copy; Brewed &amp; Co.</span></footer>
  </div>`;
}
