import {escapeHtml as h} from './ui.js';
import {icon} from './icons.js';

export function renderCustomerAuth(mode = 'login', message = '') {
  const registering = mode === 'register';
  return `<section class="customer-auth-page"><div class="customer-auth-art"><a class="story-footer-brand" href="#home" data-section="home">Brewed <em>&amp;</em> Co.</a><span class="story-eyebrow">${icon('coffee')} YOUR COFFEE, YOUR WAY</span><h1>${registering ? 'A little more<br><em>personal.</em>' : 'Welcome back<br><em>to your ritual.</em>'}</h1><p>Save your details and make every coffee break feel like yours.</p><div class="auth-coffee-card"><img src="/img/coffee3.png" alt="Freshly made latte"><span>Made slowly. Enjoyed fully.</span></div></div><div class="customer-auth-panel"><form id="customerAuthForm" class="customer-auth-card"><a class="auth-back" href="#home" data-section="home">${icon('arrowLeft')} Back to menu</a><span class="story-eyebrow">${registering ? 'CREATE AN ACCOUNT' : 'CUSTOMER SIGN IN'}</span><h2>${registering ? 'Join us.' : 'Good to see you.'}</h2><p>${registering ? 'Create your account to keep your details close.' : 'Sign in to your Brewed & Co. account.'}</p>${registering ? `<label for="customerName">Your name</label><input id="customerName" name="name" autocomplete="name" placeholder="Jamie Taylor" required maxlength="120">` : ''}<label for="customerEmail">Email address</label><input id="customerEmail" name="email" type="email" autocomplete="email" placeholder="you@example.com" required maxlength="254"><label for="customerPassword">Password</label><input id="customerPassword" name="password" type="password" autocomplete="${registering ? 'new-password' : 'current-password'}" placeholder="${registering ? 'At least 8 characters' : 'Your password'}" required minlength="${registering ? '8' : '1'}" maxlength="256">${message ? `<div class="customer-auth-error" role="alert">${h(message)}</div>` : ''}<button class="customer-auth-submit" type="submit">${registering ? 'Create account' : 'Sign in'} ${icon('arrow')}</button><p class="customer-auth-switch">${registering ? 'Already have an account?' : 'New to Brewed & Co.?'} <button type="button" data-action="${registering ? 'customer-login' : 'customer-register'}">${registering ? 'Sign in' : 'Create an account'}</button></p><small class="auth-secure-note">${icon('check')} Your password is stored securely.</small></form></div></section>`;
}

export function renderContactPage(contact = {}) {
  const rows = [['location', contact.address], ['clock', contact.hours], ['contact', contact.phone], ['contact', contact.email], ['arrow', contact.website]].filter(([, value]) => value);
  return `<section class="contact-page"><div class="contact-page-heading"><span class="story-eyebrow">${icon('location')} WE'D LOVE TO HEAR FROM YOU</span><h1>Come say <em>hello.</em></h1><p>Questions about a drink, an order, or just want to talk coffee? Leave us a note and our team will get back to you.</p></div><div class="contact-page-grid"><aside class="contact-details-card"><span class="story-eyebrow">${icon('coffee')} ${h(contact.name || 'Brewed & Co.')}</span><h2>A good cup<br>starts here.</h2><p>Thoughtful coffee, warm welcomes, and room for one more at the table.</p>${rows.length ? rows.map(([glyph, value]) => `<div class="contact-detail-row">${icon(glyph)}<span>${h(value)}</span></div>`).join('') : '<p class="contact-placeholder">Visit us soon for a cup made fresh to order.</p>'}<button class="story-primary" data-action="browse">${icon('coffee')} Browse the menu ${icon('arrow')}</button></aside><form id="contactMessageForm" class="contact-message-card"><span class="story-eyebrow">SEND A NOTE</span><h2>How can we help?</h2><label for="contactName">Your name</label><input id="contactName" name="name" autocomplete="name" required maxlength="120" placeholder="Jamie Taylor"><label for="contactEmail">Email address</label><input id="contactEmail" name="email" type="email" autocomplete="email" required maxlength="254" placeholder="you@example.com"><label for="contactSubject">Subject <small>Optional</small></label><input id="contactSubject" name="subject" maxlength="160" placeholder="A little about your message"><label for="contactMessage">Your message</label><textarea id="contactMessage" name="message" required maxlength="5000" rows="5" placeholder="Write your note here..."></textarea><button class="customer-auth-submit" type="submit">Send message ${icon('arrow')}</button><p class="contact-form-note">We’ll save your message for the café team.</p></form></div></section>`;
}

export function renderCustomerAccount(user) {
  return `<section class="customer-account-page"><div class="customer-account-card"><span class="account-avatar">${h((user?.name || 'C').slice(0, 1).toUpperCase())}</span><span class="story-eyebrow">YOUR BREWED &amp; CO. ACCOUNT</span><h1>Welcome, <em>${h(user?.name || 'coffee lover')}.</em></h1><p>You’re signed in as <b>${h(user?.email || '')}</b>.</p><div class="account-perks"><span>${icon('check')} Your account is ready</span><span>${icon('coffee')} Your next coffee is waiting</span></div><button class="customer-auth-submit" data-action="customer-logout">Sign out ${icon('arrow')}</button><button class="contact-account-link" data-section="menu">Explore the coffee menu ${icon('arrow')}</button></div></section>`;
}
